openapi: 3.0.0
info:
  title: To Do List
  contact: {}
  version: "1.0"
servers:
  - url: https://mgamboa-to-do.herokuapp.com/api/v1
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register
      operationId: Register
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
            example:
              name: Marcus
              email: test1@gmail.com
              password: password123
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
            example:
              email: test1@gmail.com
              password: password123
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /items:
    get:
      tags:
        - Items
      summary: Get All Items
      operationId: GetAllItems
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    post:
      tags:
        - Items
      summary: Create Item
      operationId: CreateItem
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateItemRequest"
            example:
              name: dishes1
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /items/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The item ID
    delete:
      tags:
        - Items
      summary: Delete Item
      operationId: DeleteItem
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    patch:
      tags:
        - Items
      summary: Update Item
      operationId: UpdateItem
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateItemRequest"
            example:
              name: dishes3
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
components:
  schemas:
    LoginRequest:
      title: LoginRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: test1@gmail.com
        password: password123
    RegisterRequest:
      title: RegisterRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Marcus
        email: test2@gmail.com
        password: password123
    CreateItemRequest:
      title: CreateItemRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
      example:
        name: dishes1
    UpdateItemRequest:
      title: UpdateItemRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
      example:
        name: dishes3
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Auth
    description: ""
  - name: Items
    description: ""
